/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#64ffda",
        "secondary-container": "#374767",
        "slate-dark": "#0a192f",
        "surface": "#041329",
        "error-container": "#93000a",
        "surface-container-high": "#1c2a41",
        "on-secondary-fixed-variant": "#374767",
        "secondary": "#b6c6ed",
        "on-background": "#d6e3ff",
        "on-error": "#690005",
        "inverse-primary": "#006b58",
        "on-primary-container": "#00725e",
        "on-tertiary": "#393000",
        "surface-bright": "#2c3951",
        "primary": "#ffffff",
        "surface-dim": "#041329",
        "surface-container-lowest": "#010e24",
        "on-primary-fixed": "#002019",
        "on-secondary-fixed": "#091b39",
        "on-primary-fixed-variant": "#005142",
        "surface-container": "#112036",
        "primary-fixed": "#64ffda",
        "on-error-container": "#ffdad6",
        "on-surface": "#d6e3ff",
        "on-secondary": "#20304f",
        "tertiary-fixed": "#fbe273",
        "surface-container-low": "#0d1c32",
        "secondary-fixed-dim": "#b6c6ed",
        "on-tertiary-fixed-variant": "#534600",
        "outline-variant": "#3c4a45",
        "tertiary-container": "#fbe273",
        "surface-variant": "#27354c",
        "on-tertiary-container": "#756400",
        "inverse-surface": "#d6e3ff",
        "primary-fixed-dim": "#64ffda",
        "secondary-fixed": "#d8e2ff",
        "tertiary": "#ffffff",
        "error": "#ffb4ab",
        "on-primary": "#00382d",
        "on-surface-variant": "#bacac3",
        "inverse-on-surface": "#233148",
        "tertiary-fixed-dim": "#dec65a",
        "on-tertiary-fixed": "#211b00",
        "slate-light": "#ccd6f6",
        "teal-tint": "rgba(100, 255, 218, 0.1)",
        "surface-tint": "#64ffda",
        "surface-container-highest": "#27354c",
        "on-secondary-container": "#a5b5db",
        "background": "#041329",
        "outline": "#85948e",
        "slate-muted": "#8892b0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "unit": "4px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-xl": ["JetBrains Mono"],
        "code-md": ["Space Mono"],
        "label-caps": ["Space Mono"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["JetBrains Mono"],
        "headline-lg": ["JetBrains Mono"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "code-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
